    // g.updateVertex(2,"KA");
    // g.checkIfNeighbour(1,3);
    // g.checkIfNeighbour(2,4);
    // g.printGraph();
    // g.printNeighbours(3);
    // g.deleteEdge(1,3);
    // // g.deleteEdge(2,3);
    // g.updateEdge(1,4,10000);
    // g.printNeighbours(1);
    // // g.deleteVertex(2);
    // // g.deleteVertex(3);
    // // g.deleteVertex(1);
    // g.printGraph();
    // g.BFSTraversal(7);
    // cout<<endl;